checks:
    php:
        scope_indentation:
            spaces_per_level: 4

tools:

    # https://scrutinizer-ci.com/docs/tools/php/security-advisory-checker/
    sensiolabs_security_checker: true

    # https://scrutinizer-ci.com/docs/tools/php/code-sniffer/
    php_code_sniffer:
        enabled: true
        command: phpcs
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'
        config:
            standard: PSR2
        # path_configs:
        #     spec:
        #         paths: ['spec/*']
        #         enabled: true
        #         config:
        #             standard: PSR2
        #             sniffs:
        #                 generic:
        #                     naming_conventions:
        #                         camel_caps_function_name_sniff: false

    # https://scrutinizer-ci.com/docs/tools/php/copy-paste-detector/
    php_cpd:
        enabled: true
        command: phpcpd
        excluded_dirs:
            - 'bin/*'
            - 'vendor/*'
            - 'features/*'

    # https://scrutinizer-ci.com/docs/tools/php/cs-fixer/
    php_cs_fixer:
        enabled: true
        command: php-cs-fixer
        config:
            level: psr2
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    # https://scrutinizer-ci.com/docs/tools/php/mess-detector/
    php_mess_detector:
        enabled: true
        command: phpmd
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    # https://scrutinizer-ci.com/docs/tools/php/pdepend/
    php_pdepend:
        enabled: true
        command: pdepend
        excluded_dirs:
            - bin
            - vendor
            - features

    # https://scrutinizer-ci.com/docs/tools/php/php-analyzer/
    php_analyzer:
        enabled: false
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'
